# Generated by Django 3.2.9 on 2021-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0006_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blogengine.Tag'),
        ),
    ]
