# Generated by Django 3.2.9 on 2021-12-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0008_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='Фото'),
        ),
    ]
