# Generated by Django 3.2.9 on 2021-12-08 09:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0009_alter_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_1',
            field=tinymce.models.HTMLField(default='', verbose_name='content1'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
