# Generated by Django 3.2.9 on 2021-12-08 09:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0010_auto_20211208_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_1',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='content1'),
        ),
    ]
