# Generated by Django 3.2.9 on 2021-12-08 09:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0011_auto_20211208_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='Содержание'),
        ),
    ]
