# Generated by Django 3.2.9 on 2021-12-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0012_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
